# Generated by Django 3.1 on 2020-09-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tomapp.invoice', verbose_name='sub WIP id'),
        ),
    ]
